// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEP490_G52_CSMS.Models;

#nullable disable

namespace SEP490_G52_CSMS.Migrations
{
    [DbContext(typeof(CSMSAppDbContext))]
    [Migration("20260723030257_AddBankTransferRevenueToHandover")]
    partial class AddBankTransferRevenueToHandover
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.AttendanceLog", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<decimal?>("CheckInConfidence")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("check_in_confidence");

                    b.Property<string>("CheckInStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("check_in_status");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_time");

                    b.Property<decimal?>("CheckOutConfidence")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("check_out_confidence");

                    b.Property<string>("CheckOutStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("check_out_status");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_out_time");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsFaceCheckInValid")
                        .HasColumnType("bit")
                        .HasColumnName("is_face_check_in_valid");

                    b.Property<bool>("IsFaceCheckOutValid")
                        .HasColumnType("bit")
                        .HasColumnName("is_face_check_out_valid");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("overall_status");

                    b.Property<int>("RosterId")
                        .HasColumnType("int")
                        .HasColumnName("roster_id");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RosterId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("attendance_logs");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.CashHandover", b =>
                {
                    b.Property<int>("HandoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("handover_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HandoverId"));

                    b.Property<decimal>("ActualCash")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_cash");

                    b.Property<decimal>("BankTransferRevenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("bank_transfer_revenue");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch_id");

                    b.Property<string>("BranchId1")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("HandoverDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("handover_date");

                    b.Property<int>("IncomingCashierId")
                        .HasColumnType("int")
                        .HasColumnName("incoming_cashier_id");

                    b.Property<decimal>("InitialCash")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("initial_cash");

                    b.Property<bool>("IsPasswordConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("is_password_confirmed");

                    b.Property<decimal>("MachineCashRevenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("machine_cash_revenue");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("opened_at");

                    b.Property<int>("OutgoingCashierId")
                        .HasColumnType("int")
                        .HasColumnName("outgoing_cashier_id");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TheoreticalCash")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("theoretical_cash");

                    b.HasKey("HandoverId");

                    b.HasIndex("BranchId");

                    b.HasIndex("BranchId1");

                    b.HasIndex("IncomingCashierId");

                    b.HasIndex("OutgoingCashierId");

                    b.HasIndex("ShiftId");

                    b.ToTable("cash_handovers");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.FixedShift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shift_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shift_name");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("ShiftId");

                    b.ToTable("fixed_shifts");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.LeaveApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("application_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("ApprovedBranchId")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("approved_branch_id");

                    b.Property<int?>("ApprovedManagerId")
                        .HasColumnType("int")
                        .HasColumnName("approved_manager_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.HasKey("ApplicationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ApprovedBranchId", "ApprovedManagerId");

                    b.ToTable("leave_applications");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.ShiftChangeRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("ApprovedBranchId")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("approved_branch_id");

                    b.Property<int?>("ApprovedManagerId")
                        .HasColumnType("int")
                        .HasColumnName("approved_manager_id");

                    b.Property<string>("Aspiration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aspiration");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<int>("RequestingEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("requesting_employee_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestingEmployeeId");

                    b.HasIndex("ApprovedBranchId", "ApprovedManagerId");

                    b.ToTable("shift_change_requests");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.WeeklyRosterGrid", b =>
                {
                    b.Property<int>("RosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roster_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RosterId"));

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assignment_date");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id");

                    b.HasKey("RosterId");

                    b.HasIndex("BranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("weekly_roster_grids");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Core.Branch", b =>
                {
                    b.Property<string>("BranchId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("branch_name");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time")
                        .HasColumnName("closing_time");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time")
                        .HasColumnName("opening_time");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("BranchId");

                    b.HasIndex("BranchName")
                        .IsUnique();

                    b.ToTable("branches");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Employees.BranchManager", b =>
                {
                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch_id");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<DateTime>("AppointedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointed_date");

                    b.HasKey("BranchId", "ManagerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("branch_managers");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Employees.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch_id");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("citizen_id");

                    b.Property<string>("ContractFilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contract_file_path");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("employment_type");

                    b.Property<string>("FaceData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("face_data");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockout_until");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CitizenId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("employees");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.BranchMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("menu_name");

                    b.HasKey("MenuId");

                    b.HasIndex("BranchId");

                    b.ToTable("branch_menus");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.MasterProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("master_products");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.MenuDetail", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("MenuId", "VariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("menu_details");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch_id");

                    b.Property<string>("BrewingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("brewing_status");

                    b.Property<int>("CashierId")
                        .HasColumnType("int")
                        .HasColumnName("cashier_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("OrderId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CashierId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.OrderItem", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("order_id");

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderId", "VariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("category_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("product_categories");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.ProductVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("selling_price");

                    b.Property<string>("SizeVariant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("size_variant");

                    b.HasKey("VariantId");

                    b.HasIndex("ProductId", "SizeVariant")
                        .IsUnique();

                    b.ToTable("product_variants");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.AttendanceLog", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Employees.Employee", "Employee")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Attendance.WeeklyRosterGrid", "WeeklyRosterGrid")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("WeeklyRosterGrid");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.CashHandover", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Core.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Core.Branch", null)
                        .WithMany("CashHandovers")
                        .HasForeignKey("BranchId1");

                    b.HasOne("SEP490_G52_CSMS.Models.Employees.Employee", "IncomingCashier")
                        .WithMany()
                        .HasForeignKey("IncomingCashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Employees.Employee", "OutgoingCashier")
                        .WithMany()
                        .HasForeignKey("OutgoingCashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Attendance.FixedShift", "FixedShift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("FixedShift");

                    b.Navigation("IncomingCashier");

                    b.Navigation("OutgoingCashier");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.LeaveApplication", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Employees.Employee", "Employee")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Employees.BranchManager", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBranchId", "ApprovedManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.ShiftChangeRequest", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Employees.Employee", "RequestingEmployee")
                        .WithMany()
                        .HasForeignKey("RequestingEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Employees.BranchManager", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBranchId", "ApprovedManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Approver");

                    b.Navigation("RequestingEmployee");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.WeeklyRosterGrid", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Core.Branch", "Branch")
                        .WithMany("WeeklyRosterGrids")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Employees.Employee", "Employee")
                        .WithMany("WeeklyRosterGrids")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Attendance.FixedShift", "FixedShift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Employee");

                    b.Navigation("FixedShift");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Employees.BranchManager", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Core.Branch", "Branch")
                        .WithMany("BranchManagers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Employees.Employee", "Manager")
                        .WithMany("ManagedBranches")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Employees.Employee", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Core.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.BranchMenu", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Core.Branch", "Branch")
                        .WithMany("BranchMenus")
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.MasterProduct", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Sales.ProductCategory", "ProductCategory")
                        .WithMany("MasterProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.MenuDetail", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Sales.BranchMenu", "BranchMenu")
                        .WithMany("MenuDetails")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Sales.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchMenu");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.Order", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Core.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("BranchId");

                    b.HasOne("SEP490_G52_CSMS.Models.Employees.Employee", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.OrderItem", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Sales.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEP490_G52_CSMS.Models.Sales.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.ProductVariant", b =>
                {
                    b.HasOne("SEP490_G52_CSMS.Models.Sales.MasterProduct", "MasterProduct")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterProduct");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Attendance.WeeklyRosterGrid", b =>
                {
                    b.Navigation("AttendanceLogs");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Core.Branch", b =>
                {
                    b.Navigation("BranchManagers");

                    b.Navigation("BranchMenus");

                    b.Navigation("CashHandovers");

                    b.Navigation("Employees");

                    b.Navigation("Orders");

                    b.Navigation("WeeklyRosterGrids");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Employees.Employee", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("LeaveApplications");

                    b.Navigation("ManagedBranches");

                    b.Navigation("WeeklyRosterGrids");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.BranchMenu", b =>
                {
                    b.Navigation("MenuDetails");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.MasterProduct", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SEP490_G52_CSMS.Models.Sales.ProductCategory", b =>
                {
                    b.Navigation("MasterProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
